version: "3.9"
services:

    nginx:
        container_name: "${APP_TITLE}"
        image: nginx:latest
        ports:
            - "${APP_PORT}:80"
        links:
            - php
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/usr/share/nginx/www

    php:
        container_name: "${APP_NAME}"
        hostname: blog
        build: .
        volumes:
            - ./:/usr/share/nginx/www

networks:
    default:
        external: true
        name: ${APP_DOCKER_NETWORK}
