version: "3.9"
services:

    nginx:
        container_name: blog
        build: ./docker/nginx
        links:
            - php
        volumes:
            - ./:/usr/share/nginx/www

    php:
        container_name: "php-${APP_TITLE}"
        build: ./docker/php
        volumes:
            - ./:/usr/share/nginx/www

networks:
    default:
        external: true
        name: ${APP_DOCKER_NETWORK}
